#!/usr/bin/env bash


mkdir -p tests/outs

bin/$1 tests/$2.vera | tail -n 1 > tests/outs/$2_$1.txt


diff tests/targets/$2.txt tests/outs/$2_$1.txt &> /dev/null


if [[ "$?" == 0 ]]; then
    echo -ne "\033[42m\033[30m PASS \033[0m"
else
    echo -ne "\033[41m\033[30m FAIL \033[0m"
fi

echo " ... $2.vera"
