#!/usr/bin/env bash

# take the specified test list file and break out into separate test command
# files and expected command output files.
#
# Each test is a command/output pair, delineated by 50 -'s:
# --------------------------------------------------
# 
# and each distinct test is delineated by 50 ='s:
# ==================================================
#
# test list files are from tests/lists, and each separate test is added into
# tests/splits. Final separated command and output files go into tests/runs,
# with the output file suffixed '_target'

mkdir -p "tests/splits/$1"  # makefile target, tests/lists/$1 will be dependency
mkdir -p tests/runs

rm -rf "tests/runs/$1_*"
echo "Splitting tests/lists/$1..."

# split up each command/target pair into tests/splits
csplit \
  --prefix "tests/splits/$1/$1" \
  --suppress-matched \
  --quiet \
  --elide-empty-files \
  "tests/lists/$1" '/==================================================/' '{*}' \

# then go in and split up the command from the target into separate files in
# tests/runs
for file in "tests/splits/$1"/*; do
  filename=$(basename "$file")
  echo "Splitting $file... to tests/runs/${filename}_"
  csplit \
    --prefix "tests/runs/${filename}_" \
    --suppress-matched \
    --quiet \
    --elide-empty-files \
    "$file" '/--------------------------------------------------/' '{*}'
done;

# rename all of the target files as _target (with same prefix as command file)
for file in tests/runs/*1; do
  mv "$file" "${file::(-1)}0_target"
done
